### ISSUE TITLE
Negating Gradients

### ISSUE THREAD

**Issue by bhairavmehta95** [cics-nd/cnn-surrogate#1]
Hi @bmmi - thanks for your code. Would you be able to explain why you are negating the gradients here?

https://github.com/cics-nd/cnn-surrogate/blob/master/models/svgd.py#L163

Doesn't pytorch take care of this for you?

**Comment by yinhaoz** [comment]
Hi Bhairav,

The gradient calculated with the equation (8) in https://arxiv.org/abs/1608.04471 is the steepest descent direction of the KL divergence for the current step, not like the usual case where the gradient obtained with autograd is the direction to maximize the loss.

**Comment by bhairavmehta95** [comment]
Thanks!
