### ISSUE TITLE
Failed to download dataset

### ISSUE THREAD

**Issue by rafaelstevenson** [cics-nd/cnn-surrogate#4]
Hello, is the dataset still available to download as i have failed to download using the command 
bash ./scripts/download_dataset.sh 4225

**Comment by rafaelstevenson** [comment]
![image](https://user-images.githubusercontent.com/67007111/120667387-a4549d00-c4b7-11eb-834f-2e1a11e978e6.png)

**Comment by yinhaoz** [comment]
Hi Rafael, looks like `wget` is not installed in your system. I have no problem downloading the dataset.

**Comment by rafaelstevenson** [comment]
Hello, i see, it is working now, thank you very much for your help.
